"""initial schema

Revision ID: 17643bb7471c
Revises: 
Create Date: 2026-09-04 13:50:20.776871
"""
from alembic import op
import sqlalchemy as sa


revision = '17643bb7471c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_events',
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_level'), 'system_events', ['level'], unique=False)
    op.create_index(op.f('ix_system_events_source'), 'system_events', ['source'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'business', 'enterprise', name='subscriptionplan', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_created_at'), 'subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('telegram_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', 'disconnected', 'restricted', name='telegramaccountstatus', native_enum=False, length=16), nullable=False),
    sa.Column('session_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_hash_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restricted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_accounts_created_at'), 'telegram_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_status'), 'telegram_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_telegram_user_id'), 'telegram_accounts', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_accounts_user_id'), 'telegram_accounts', ['user_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operations_count', sa.Integer(), nullable=False),
    sa.Column('members_processed', sa.Integer(), nullable=False),
    sa.Column('connected_accounts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_period_start'), 'usage_records', ['period_start'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verification', 'password_reset', name='usertokenpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_created_at'), 'user_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_tokens_token_hash'), 'user_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    op.create_table('telegram_chats',
    sa.Column('telegram_account_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('chat_type', sa.Enum('group', 'supergroup', 'channel', name='chattype', native_enum=False, length=16), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('can_invite_users', sa.Boolean(), nullable=False),
    sa.Column('admin_rights', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('members_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_account_id', 'telegram_chat_id', name='uq_chat_per_account')
    )
    op.create_index(op.f('ix_telegram_chats_created_at'), 'telegram_chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_chats_telegram_account_id'), 'telegram_chats', ['telegram_account_id'], unique=False)
    op.create_index(op.f('ix_telegram_chats_telegram_chat_id'), 'telegram_chats', ['telegram_chat_id'], unique=False)
    op.create_table('migrations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_account_id', sa.Uuid(), nullable=False),
    sa.Column('source_chat_id', sa.Uuid(), nullable=True),
    sa.Column('destination_chat_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('draft', 'queued', 'running', 'paused', 'completed', 'cancelled', 'failed', name='migrationstatus', native_enum=False, length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('total_selected', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('successful', sa.Integer(), nullable=False),
    sa.Column('already_member', sa.Integer(), nullable=False),
    sa.Column('privacy_restricted', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('worker_task_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['destination_chat_id'], ['telegram_chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_chat_id'], ['telegram_chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telegram_account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migrations_created_at'), 'migrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_migrations_destination_chat_id'), 'migrations', ['destination_chat_id'], unique=False)
    op.create_index(op.f('ix_migrations_source_chat_id'), 'migrations', ['source_chat_id'], unique=False)
    op.create_index(op.f('ix_migrations_status'), 'migrations', ['status'], unique=False)
    op.create_index(op.f('ix_migrations_telegram_account_id'), 'migrations', ['telegram_account_id'], unique=False)
    op.create_index(op.f('ix_migrations_user_id'), 'migrations', ['user_id'], unique=False)
    op.create_table('telegram_members',
    sa.Column('telegram_chat_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('last_seen_bucket', sa.Enum('online', 'recently', 'within_week', 'within_month', 'long_ago', 'hidden', name='lastseenbucket', native_enum=False, length=16), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_chat_id'], ['telegram_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id', 'telegram_user_id', name='uq_member_per_chat')
    )
    op.create_index(op.f('ix_telegram_members_created_at'), 'telegram_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_members_telegram_chat_id'), 'telegram_members', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_members_telegram_user_id'), 'telegram_members', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_telegram_members_username'), 'telegram_members', ['username'], unique=False)
    op.create_table('migration_members',
    sa.Column('migration_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_member_id', sa.Uuid(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('result', sa.Enum('pending', 'success', 'already_member', 'privacy_restricted', 'permission_denied', 'flood_wait', 'invalid_user', 'failed', 'skipped', name='migrationmemberresult', native_enum=False, length=24), nullable=False),
    sa.Column('telegram_error', sa.Text(), nullable=True),
    sa.Column('flood_wait_seconds', sa.Integer(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telegram_member_id'], ['telegram_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migration_members_created_at'), 'migration_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_migration_members_migration_id'), 'migration_members', ['migration_id'], unique=False)
    op.create_index(op.f('ix_migration_members_result'), 'migration_members', ['result'], unique=False)
    op.create_index(op.f('ix_migration_members_telegram_member_id'), 'migration_members', ['telegram_member_id'], unique=False)
    op.create_index(op.f('ix_migration_members_telegram_user_id'), 'migration_members', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_migration_members_telegram_user_id'), table_name='migration_members')
    op.drop_index(op.f('ix_migration_members_telegram_member_id'), table_name='migration_members')
    op.drop_index(op.f('ix_migration_members_result'), table_name='migration_members')
    op.drop_index(op.f('ix_migration_members_migration_id'), table_name='migration_members')
    op.drop_index(op.f('ix_migration_members_created_at'), table_name='migration_members')
    op.drop_table('migration_members')
    op.drop_index(op.f('ix_telegram_members_username'), table_name='telegram_members')
    op.drop_index(op.f('ix_telegram_members_telegram_user_id'), table_name='telegram_members')
    op.drop_index(op.f('ix_telegram_members_telegram_chat_id'), table_name='telegram_members')
    op.drop_index(op.f('ix_telegram_members_created_at'), table_name='telegram_members')
    op.drop_table('telegram_members')
    op.drop_index(op.f('ix_migrations_user_id'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_telegram_account_id'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_status'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_source_chat_id'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_destination_chat_id'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_created_at'), table_name='migrations')
    op.drop_table('migrations')
    op.drop_index(op.f('ix_telegram_chats_telegram_chat_id'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_telegram_account_id'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_created_at'), table_name='telegram_chats')
    op.drop_table('telegram_chats')
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_token_hash'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_created_at'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_period_start'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_telegram_accounts_user_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_telegram_user_id'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_status'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_created_at'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_created_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_events_source'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_level'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    # ### end Alembic commands ###
